spring:
  application:
    name: activityservice
    data:
      mongodb:
        uri : mongodb://localhost:27017/activefitness
        database : activefitness

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/

kafka:
 topic:
   name: activity-events