spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.header: false
        spring.json.value.default.type: com.fitness.aiservice.Models.Activity
        spring.json.trusted.packages: "*"

# Custom Configs
gemini:
  api:
    url: ${GEMINI_URL}
    key: ${GEMINI_KEY}

kafka:
  topic:
    name: activity-topic

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/